### ISSUE TITLE
[New Test Runner] Erlang

### ISSUE THREAD

**Issue by NobbZ** [exercism/automated-tests#10]
I'm participating in exercism since 5 years now and do maintain the Erlang track as well as mentoring Erlang and Elixir on an irregular base.

Providing a bare docker image that is able to run the tests and spit out the bare result should be very easy, while at the same time I think it will be very interesting to build a formatter that will be able to also give us some custom output.

Either way, I'm looking forward to this.

**Comment by iHiD** [comment]
Thanks! :) https://github.com/exercism/erlang-test-runner

**Comment by iHiD** [comment]
@NobbZ Want to play with elixir too?

**Comment by NobbZ** [comment]
Yeah, I like to help there as well.

**Comment by iHiD** [comment]
Great. https://github.com/exercism/elixir-test-runner :)
