### ISSUE TITLE
Not definitively clear whether test files are provided in the solution folder

### ISSUE THREAD

**Issue by alirezaghey** [exercism/automated-tests#20]
I may be wrong, but I couldn't find a definitive answer on whether the test files are also included in the solution folder that is provided to the test runners.

Currently, we are assuming that the test files are included in the solution folder. If that's correct, it would be helpful to add this to the docs to avoid confusion.

Or I may be wrong and this is already obvious?

Thanks!

**Comment by iHiD** [comment]
> we are assuming that the test files are included in the solution folder

That's correct :)

**Comment by iHiD** [comment]
Feel free to PR the interface to make this clear btw :)
