### ISSUE TITLE
[New Test Runner] Bash

### ISSUE THREAD

**Issue by bkhl** [exercism/automated-tests#30]
Hello,

I'm Björn, I've been mentoring on and off on the Bash and Python tracks for a while.

I started work on a test runner for Bash already here: https://github.com/bkhl/bash-test-runner . I'll move it over if you approve of this as a starting point.

**Comment by iHiD** [comment]
Great. Thanks!

I've created https://github.com/exercism/bash-test-runner and invited you to a team to maintain it. :)

**Comment by bkhl** [comment]
I've joined, but looks like you need to promote me somehow. I only have read access for now.

**Comment by iHiD** [comment]
Sorry. Sorted now.
