### ISSUE TITLE
[New Test Runner] Elixir

### ISSUE THREAD

**Issue by neenjaw** [exercism/automated-tests#31]
Hey I think i have done the local testing of the elixir test runner, and I think the docker image successfully builds, then subsequently runs as expected according to the interface and docker readme.

What are the next steps from here as far as integration testing?

**Comment by iHiD** [comment]
We don't have any of these live yet, so there aren't next steps. But we'll include this in the first tranche, which should be in the next few weeks :)

**Comment by iHiD** [comment]
I believe this has long been done, so I'll close :)
