### ISSUE TITLE
[New Test Runner] - Ruby, Rust, Go, Elixir

### ISSUE THREAD

**Issue by rabotyaga** [exercism/automated-tests#4]
I've just start mentoring on these tracks but I have some experience with CI/CD and automated code review tools for these languages.

**Comment by tehsphinx** [comment]
Maybe create one issue per language so they can be discussed individually?

**Comment by tehsphinx** [comment]
I'm gonna make the Go one as I was just about to do that anyway: https://github.com/exercism/automated-tests/issues/9

**Comment by tehsphinx** [comment]
Note that Rust also exists already: https://github.com/exercism/automated-tests/issues/5

**Comment by rabotyaga** [comment]
Hi, @tehsphinx!
You are absolutely right. I've just expressed readiness to help with those tracks if it would be needed.

**Comment by iHiD** [comment]
@rabotyaga Thanks! So there are now repos for all those (e.g. https://github.com/exercism/go-test-runner). I've given write access to the track maintainers, and once you've done a little work on them (either through issues here or on Slack) then I'd be happy to give you write access too :)
