### ISSUE TITLE
[New Test Runner] Java

### ISSUE THREAD

**Issue by msomji** [exercism/automated-tests#44]
I am a maintainer on the java track and am in the process of working on implementing the [java test runner](https://github.com/exercism/java-test-runner) but it appears the repo has not been initialized yet for me be pull it down/create PRs etc. Would someone be able to initialize that repository/ give me the appropriate access to be able to do so. Thanks!

**Comment by ErikSchierboom** [comment]
@iHiD will take care of this for you!

**Comment by msomji** [comment]
@iHiD would you be able to help with this 🙂

**Comment by iHiD** [comment]
@msomji I've added you to the team so you can just push a first commit up with a README or something :)
