### ISSUE TITLE
[New Test Runner] Clojure

### ISSUE THREAD

**Issue by porkostomus** [exercism/automated-tests#46]
Hi, I'd like to start building the Clojure test runner. As an active member of the Clojurians Slack, I'm in daily contact with the tooling authors, who are eager to answer all my questions! Although, I find that I very rarely have to bother them because most things just work, and are always so well documented that the answer is usually right there.

**Comment by iHiD** [comment]
Thanks! :) https://github.com/exercism/clojure-test-runner
