### ISSUE TITLE
[New Test Runner]  Nim test-runner

### ISSUE THREAD

**Issue by ynfle** [exercism/automated-tests#50]
Hi I'm Yoni and I recently became a mentor on the Python track. I have been programming for 7 years now (primarily Python) and am in the middle of a undergraduate software engineering degree.
I discovered nim a little while ago and feel in love with is simple metaprogramming ideas and readability (coming from a Python background).
I would like to make a test-runner for nim so it could be part of the v3 version of exercism.

**Comment by iHiD** [comment]
Here you go! :) https://github.com/exercism/nim-test-runner
